services:
  serve:
    build:
      context: .
    container_name: serve_app
    command: python src/serve.py
    ports:
      - "8000:8000"

  raggpt:
    build:
      context: .
    container_name: raggpt_app
    command: python src/raggpt_app.py
    ports:
      - "8001:8001"
    volumes:
      - .:/app
